server:
  port: 9000

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/gy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://192.168.10.161:3306/gy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates


mybatis:
  type-aliases-package: com.lw.pojo
  configuration:
    map-underscore-to-camel-case: true
